StudentEvidence/Controllers/IspitController.cs
using DATA;
using StudentEvidence.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentEvidence.Controllers
{
    [Authorize(Roles = "admin")]
    public class IspitController : Controller
    {
        DALIspit dalIspit = new DALIspit();
        DALPredmet dalPredmet = new DALPredmet();
        DALStudent dalStudent = new DALStudent();
        // GET: Ispit
        public ActionResult Index()
        {
            var ispiti = dalIspit.getAllIspit().ToList();
            List<IspitModel> model = new List<IspitModel>();
            foreach (var item in ispiti)
            {
                model.Add(new IspitModel()
                {
                    ID = item.ID,
                    DatumPolaganja = item.DatumPolaganja,
                    Ocena = item.Ocena,
                    Student = new StudentModel() { Ime = item.Student.Ime, Prezime = item.Student.Prezime },
                    Predmet = new PredmetModel() { Naziv = item.Predmet.Naziv }

                });
            }
            return View(model);


        }
        public ActionResult AddIspit()
        {
            var getPredmets = dalPredmet.getAllPredmet();
            var getStudents = dalStudent.getAllStudent();
            List<PredmetModel> predmetModel = new List<PredmetModel>() ;
            List<StudentModel> studentModel = new List<StudentModel>();
            foreach (var item in getPredmets)
            {
                predmetModel.Add(new PredmetModel()
                {
                    ID = item.ID,
                    Naziv = item.Naziv
                });
            }
            foreach (var item in getStudents)
            {
                studentModel.Add(new StudentModel()
                {
                    ID = item.ID,
                    Ime = item.Ime,
                    Prezime = item.Prezime,
                    BrIndexa = item.BrIndexa,
                    Grad = item.Grad
                });
            }
            return View(new IspitModel()
            {
                Studenti = studentModel,
                Predmets = predmetModel
            });
        }
        [HttpPost]
        public ActionResult AddIspit(IspitModel model)
        {
            if (ModelState.IsValid) {
                dalIspit.AddIspit(new Ispit()
                {
                    DatumPolaganja = model.DatumPolaganja,
                    ID = model.ID,
                    Ocena = model.Ocena,
                    PredmetID = model.PredmetID,
                    StudentID = model.StudentID
                });
                return RedirectToAction("Index", "ispit");
            }
            return RedirectToAction("AddIspit", "ispit");
        }
        public ActionResult DeleteIspit(int ID) {
            dalIspit.DeleteIspit(ID);
            return RedirectToAction("Index", "ispit");

        }
        [HttpPost]
        public ActionResult EditIspit(IspitModel model)
        {
            if (ModelState.IsValid) {
                dalIspit.UpdateIspit(new Ispit()
                {
                    DatumPolaganja = model.DatumPolaganja,
                    ID = model.ID,
                    Ocena = model.Ocena,
                    PredmetID = model.PredmetID,
                    StudentID = model.StudentID
                });
                return RedirectToAction("Index", "ispit");
            }

            return RedirectToAction("EditIspit", "ispit", new { ID = model.ID });
        }
        public ActionResult EditIspit(int ID)
        {
            var getPredmets = dalPredmet.getAllPredmet();
            var getStudents = dalStudent.getAllStudent();
            List<PredmetModel> predmetModel = new List<PredmetModel>();
            List<StudentModel> studentModel = new List<StudentModel>();
            foreach (var item in getPredmets)
            {
                predmetModel.Add(new PredmetModel()
                {
                    ID = item.ID,
                    Naziv = item.Naziv
                });
            }
            foreach (var item in getStudents)
            {
                studentModel.Add(new StudentModel()
                {
                    ID = item.ID,
                    Ime = item.Ime,
                    Prezime = item.Prezime,
                    BrIndexa = item.BrIndexa,
                    Grad = item.Grad
                });
            }
            var model = dalIspit.getIspit(ID);
            return View(new IspitModel()
            {
                ID = model.ID,
                DatumPolaganja = model.DatumPolaganja,
                Ocena = model.Ocena,
                Predmet = new PredmetModel() { Naziv = model.Predmet.Naziv },
                Predmets = predmetModel,
                Studenti = studentModel
            }); 
        }
    }
}

StudentEvidence/Views/Ispit/AddIspit.cshtml
@model StudentEvidence.Models.IspitModel
@{
    ViewBag.Title = "AddIspit";
}

<h2>AddIspit</h2>

<div class="container">
    <div class="card">
        <div class="card-body mx-auto">
            @using (Html.BeginForm("AddIspit", "Ispit", FormMethod.Post, new { @class = "form-horizontal" }))
            { 

            <div class="form-group row">
                <label class="col-form-label text-primary"><small>Ocena:</small></label>
                @Html.TextBoxFor(x => x.Ocena, new { @class = "form-control", placeholder = "Ocena:", @type = "number", min = "5", max = "10" })
                @Html.ValidationMessageFor(x => x.Ocena, null, new { @style = "color:Red;" })
            </div>

                <div class="form-group">
                    <label class="col-form-label text-primary"><small>DatumPolaganja-(@Model.DatumPolaganja.ToShortDateString().Replace("/", ".")):</small></label>
                    <div class=" form-group">
                        @Html.TextBoxFor(x => x.DatumPolaganja, new { @class = "control-label" })
                        @Html.ValidationMessageFor(x => x.DatumPolaganja, null, new { @style = "color:Red;" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="row">
                        <label class="col-form-label text-primary"><small>Naziv Predmeta:</small></label>
                    </div>
                    <div class="row">
                        @Html.DropDownListFor(x => x.PredmetID, Model.Predmets.Select(x => new SelectListItem() { Text = x.Naziv, Value = x.ID.ToString() }))
                        @Html.ValidationMessageFor(x => x.PredmetID, null, new { @style = "color:Red;" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="row">
                        <label class="col-form-label text-primary"><small>Student:</small></label>
                    </div>
                    <div class="row">
                        @Html.DropDownListFor(x => x.StudentID, Model.Studenti.Select(x => new SelectListItem() { Text = x.Ime + " " + x.Prezime, Value = x.ID.ToString() }))
                        @Html.ValidationMessageFor(x => x.StudentID, null, new { @style = "color:Red;" })
                    </div>
                </div>
                 
                <div class="form-group row">
                    <div>

                        <button type="submit" class="btn btn-success">Save</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

StudentEvidence/Views/Ispit/EditIspit.cshtml
@model StudentEvidence.Models.IspitModel
@{
    ViewBag.Title = "EditIspit";
}

<h2>EditIspit - @Model.Predmet.Naziv</h2>
<div class="container">
    <div class="card">
        <div class="card-body mx-auto">
            @using (Html.BeginForm("EditIspit", "Ispit", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.HiddenFor(x => x.ID)

                <div class="form-group row">
                    <label class="col-form-label text-primary"><small>Ocena:</small></label>
                    @Html.TextBoxFor(x => x.Ocena, new { @class = "form-control", placeholder = "Ocena:" , @type = "number", min = "5", max = "10" })
                </div>

                <div class="form-group">
                    <label class="col-form-label text-primary"><small>DatumPolaganja-(@Model.DatumPolaganja.ToShortDateString().Replace("/", ".")):</small></label>
                    <div class=" form-group">
                        @Html.TextBoxFor(x => x.DatumPolaganja, new { @class = "control-label", @value = Model.DatumPolaganja})
                        
                    </div>
                </div>
                <div class="form-group row">
                    <div class="row">
                        <label class="col-form-label text-primary"><small>Naziv Predmeta:</small></label>
                    </div>
                    <div class="row">
                        @Html.DropDownListFor(x => x.PredmetID, Model.Predmets.Select(x => new SelectListItem() { Text = x.Naziv, Value = x.ID.ToString() }))
                    </div>
                </div>
                <div class="form-group row">
                    <div class="row">
                        <label class="col-form-label text-primary"><small>Student:</small></label>
                    </div>
                    <div class="row">
                        @Html.DropDownListFor(x => x.StudentID, Model.Studenti.Select(x => new SelectListItem() { Text = x.Ime+" "+x.Prezime, Value = x.ID.ToString() }))
                    </div>
                </div>

                @*<div class="form-group">
                <div class="row">
                    <label class="col-form-label text-primary"><small>Progress:</small></label>
                </div>
                <div class="row">
                    @Html.TextBoxFor(m => m.Progress, new { @type = "number", @class = "form-control", min = "0", max = "100" })
                </div>
            </div>*@
                @*<div class="form-group">
                <div class="row">
                    <label class="col-form-label text-primary"><small>Status:</small></label>
                </div>
                <div class="row">
                    @Html.DropDownListFor(x => x.Status, Model.Statuses.Select(x => new SelectListItem() { Text = x, Value = x.ToString(), Selected = Model.Status == x ? true : false }), "All statuses", new { @value = Model.Status, @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Status, "", new { @class = "errorMessage" })
                </div>
            </div>*@
                <div class="form-group row">
                    <div>

                        <button type="submit" class="btn btn-success">Save</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

StudentEvidence/Views/Ispit/Index.cshtml
@model List<StudentEvidence.Models.IspitModel>
@{
    ViewBag.Title = "Index";
}

<div>
    @Html.ActionLink("Dodaj ispit", "AddIspit", "Ispit", new { @class = "btn btn-info btn-sm" })

</div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">ID</th>
            <th scope="col">Ime i Prezime</th>
            <th scope="col">Naziv Predmeta</th>
            <th scope="col">Ocena</th>
            <th scope="col">Datum Polaganja</th> 
            <th scope="col">Action</th> 
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th></th>
                <th scope="row">@item.ID</th>
                <th scope="row">@(item.Student.Ime+" "+item.Student.Prezime)</th>
                <th scope="row">@(item.Predmet.Naziv)</th>
                <td>@item.Ocena</td>
                <td>@item.DatumPolaganja</td> 
                <td> 
                    @Html.ActionLink("Edit", "EditIspit", "Ispit", new { ID = item.ID }, new { @class = "btn btn-info btn-sm" })
                    @Html.ActionLink("Delete", "DeleteIspit", "Ispit", new { ID = item.ID }, new { @class = "btn btn-danger btn-sm" })
                     
                </td> 
            </tr>
        } 
    </tbody>
</table> 